### ISSUE TITLE
Create a splash screen

### ISSUE THREAD

**Issue by Vaishnavimore10** [Google-Developer-Student-Club-CCOEW/Flutter#1]
Create a splash screen for the Tech Tutor application. Splash Screen is the first screen that we see when we run our application. It is also known as Launch Screen. It should be visible for 2000 ms, after which login screen/home screen will be displayed (depends on if the user is logged in or not)

- Navigate to Flutter/lib/
- write your code in splashscreen.dart file

**Comment by RuchikaSuryawanshi7** [comment]
Name: Ruchika Suryawanshi 
College: MKSSS's Cummins College Of Engineering For Women, Pune
Department: TY IT
I would like to work on this issue

**Comment by vaishnavisawant57** [comment]
![tech-tutor_@disha100](https://user-images.githubusercontent.com/80047521/196966457-b0ee640d-27fe-4ca4-a41f-9aaa43258127.jpg)
Use this logo for splash screen.
