### ISSUE TITLE
Create a user choice page

### ISSUE THREAD

**Issue by Vaishnavimore10** [Google-Developer-Student-Club-CCOEW/Flutter#6]
Create a user choice page . This page will be shown after the user clicks on sign up, we will first ask the user to choose whether they are student, teacher or a parent (can select only one of the above).

- Navigate to Flutter/lib/
- write your code in userchoice.dart file

**Comment by samitkapoor** [comment]
@Vaishnavimore10 May I work on this issue?

**Comment by Vaishnavimore10** [comment]
sure!. You can work on this issue.

**Comment by Vaishnavimore10** [comment]
Your free to explore . I will get back to you if any changes are required.

**Comment by samitkapoor** [comment]
@Vaishnavimore10 okay, ill start working on it then 👍
